# Generated by Django 5.1.4 on 2025-01-13 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_verifycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifycode',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
