# Generated by Django 5.1.4 on 2025-01-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('rating', models.IntegerField(max_length=2)),
                ('ranking', models.DecimalField(decimal_places=1, max_digits=4)),
                ('image', models.FileField(blank=True, null=True, upload_to='uploads/images/')),
                ('video', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
            ],
        ),
    ]
