# Generated by Django 5.1.4 on 2025-06-05 20:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionTestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/testfile/')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500)),
                ('genre', models.CharField(choices=[('ACTION', 'Action'), ('DOCUMENTARY', 'Documentary'), ('ROMANTIC', 'Romantic'), ('DRAMA', 'Drama')], default='NEW', max_length=30)),
                ('rating', models.IntegerField(choices=[(0, '0'), (6, '6'), (12, '12'), (16, '16'), (18, '18')], default=12)),
                ('ranking', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('duration', models.FloatField(default=0.0)),
                ('image_file', models.FileField(blank=True, null=True, upload_to='uploads/thumbnails/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MovieConvertables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_120p', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
                ('video_360p', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
                ('video_720p', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
                ('video_1080p', models.FileField(blank=True, null=True, upload_to='uploads/videos/')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_convertables', to='movie.movie')),
            ],
        ),
        migrations.CreateModel(
            name='MovieProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_progress', to='movie.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
