# Generated by Django 5.1.4 on 2025-06-05 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (6, '6'), (12, '12'), (16, '16'), (18, '18')], default=12, verbose_name='Rating (FSK)'),
        ),
    ]
