# Generated by Django 5.1.4 on 2025-01-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_ranking_alter_movie_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='image',
            new_name='image_url',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='video',
            new_name='video_url',
        ),
    ]
