# Generated by Django 5.1.4 on 2025-01-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_rename_image_movie_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default='', max_length=30),
        ),
    ]
