# Generated by Django 5.1.4 on 2025-01-06 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieConvertables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_120p', models.FileField(editable=False, upload_to='')),
                ('video_360p', models.FileField(editable=False, upload_to='')),
                ('video_720p', models.FileField(editable=False, upload_to='')),
                ('video_1080p', models.FileField(editable=False, upload_to='')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_convertables', to='movie.movie')),
            ],
        ),
    ]
