# Generated by Django 5.1.4 on 2025-01-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movieconvertables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieconvertables',
            name='video_1080p',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
        migrations.AlterField(
            model_name='movieconvertables',
            name='video_120p',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
        migrations.AlterField(
            model_name='movieconvertables',
            name='video_360p',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
        migrations.AlterField(
            model_name='movieconvertables',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='uploads/videos/'),
        ),
    ]
