# Generated by Django 5.1.4 on 2025-02-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_alter_movie_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionTestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/testfile/')),
            ],
        ),
    ]
