# Generated by Django 5.1.4 on 2025-03-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_movieprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieprogress',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
