# Generated by Django 5.1.4 on 2025-05-29 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_alter_movieprogress_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image_url',
            field=models.FileField(blank=True, null=True, upload_to='uploads/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='ranking',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, '0'), (6, '6'), (12, '12'), (16, '16'), (18, '18')], default=12),
        ),
    ]
